controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index

register:
    path: /register
    controller: App\Controller\RegisterController::index

login:
    path: /login
    controller: App\Controller\SecurityController::index

add:
    path: /admin/user/add
    controller: App\Controller\SecurityController::add